import {
  Sun,
  Wind,
  Building,
  Bed,
  Palmtree,
  Castle,
  Tent,
  Snowflake,
  Mountain,
  Warehouse,
  Diamond,
  Shell,
  Waves,
  Trees,
  Coffee,
  Utensils,
  Car,
  Plane,
  Wifi,
  Tv,
  Anchor,
  Droplets,
  Dumbbell,
  Flame,
  Landmark,
  Leaf,
  PawPrint,
  Thermometer,
  Wine,
} from "lucide-react";

export const categories = [
  {
    label: "Amazing View",
    icon: Sun,
    description: "This property has an amazing view!",
  },
  {
    label: "Beach",
    icon: Shell,
    description: "This property is close to the beach!",
  },
  {
    label: "Windmills",
    icon: Wind,
    description: "This property has windmills!",
  },
  {
    label: "Modern",
    icon: Building,
    description: "This property is modern!",
  },
  {
    label: "Rooms",
    icon: Bed,
    description: "This property has many rooms!",
  },
  {
    label: "Island",
    icon: Palmtree,
    description: "This property is on an island!",
  },
  {
    label: "Skiing",
    icon: Mountain,
    description: "This property is close to a ski resort!",
  },
  {
    label: "Castles",
    icon: Castle,
    description: "This property is a castle!",
  },
  {
    label: "Camping",
    icon: Tent,
    description: "This property is close to a camping site!",
  },
  {
    label: "Arctic",
    icon: Snowflake,
    description: "This property is in the Arctic!",
  },
  {
    label: "Cave",
    icon: Mountain,
    description: "This property is in a cave!",
  },
  {
    label: "Barns",
    icon: Warehouse,
    description: "This property is a barn!",
  },
  {
    label: "Lux",
    icon: Diamond,
    description: "This property is luxurious!",
  },
  {
    label: "Surfing",
    icon: Waves,
    description: "This property is great for surfing!",
  },
  {
    label: "Forest",
    icon: Trees,
    description: "This property is surrounded by forest!",
  },
  {
    label: "Cafe Nearby",
    icon: Coffee,
    description: "This property has cafes nearby!",
  },
  {
    label: "Gourmet Kitchen",
    icon: Utensils,
    description: "This property has a gourmet kitchen!",
  },
  {
    label: "Parking",
    icon: Car,
    description: "This property has parking available!",
  },
  {
    label: "Airport Nearby",
    icon: Plane,
    description: "This property is close to an airport!",
  },
  {
    label: "Fast Wifi",
    icon: Wifi,
    description: "This property has fast WiFi!",
  },
  {
    label: "Smart TV",
    icon: Tv,
    description: "This property has a smart TV!",
  },
  {
    label: "Pool",
    icon: Droplets,
    description: "This property has a swimming pool!",
  },
  {
    label: "Hot Tub",
    icon: Thermometer,
    description: "This property has a hot tub!",
  },
  {
    label: "Gym",
    icon: Dumbbell,
    description: "This property has a fitness center or gym!",
  },
  {
    label: "Fireplace",
    icon: Flame,
    description: "This property has a cozy fireplace!",
  },
  {
    label: "Pet-friendly",
    icon: PawPrint,
    description: "This property welcomes pets!",
  },
  {
    label: "Waterfront",
    icon: Anchor,
    description: "This property is located on the waterfront!",
  },
  {
    label: "Historic",
    icon: Landmark,
    description: "This property has historical significance!",
  },
  {
    label: "Vineyard",
    icon: Wine,
    description: "This property is on or near a vineyard!",
  },

  {
    label: "Eco-friendly",
    icon: Leaf,
    description: "This property has eco-friendly features!",
  },
];
